# **Analisi esplorativa di `additional_truths.arff`**

In questo notebook viene effettuata l'analisi esplorativa del dataset `additional_truths.arff`.

Prima di procedere con il caricamento e l'analisi tramite Pandas, viene esaminata la struttura originale del file ARFF per comprenderne l'organizzazione, gli attributi presenti e la rappresentazione dei dati.

In [3]:
with open("additional_truths.arff", "r", encoding="utf-8") as file:
    for i in range(30):
        print(file.readline(), end="")

@relation trump_truths
@attribute id integer
@attribute timestamp string
@attribute text string
@attribute url string
@attribute reply_count real
@attribute retruth_count real
@attribute like_count real
@attribute external_id string
@attribute author real
@attribute time_scraped string
@data
117323511508375196,'2026-09-24 01:51:54','','https://truthsocial.com/@realDonaldTrump/117323511508375196',792.0,1849.0,7259.0,'117323511508375196',27.0,'2026-09-20 14:00:00.000000'
117323155721195611,'2026-09-24 00:21:25',"The story that the White House, or me, want to affix my name to Ford's Theatre, in Washington, D.C., where Abraham Lincoln was assassinated, is a ridiculous lie. It is FAKE NEWS! Who would possibly want a name on such a tragic place? The Dumocrats suffer from serious Trump Derangement Syndrome. They are Degenerates and Losers who make up lie after lie, and this Ford's Theatre Hoax is just another one of their never-ending, malicious falsehoods to try to discredit and demean. Thank you for your attention to this matter. President DONALD J. TRUMP",'https://truthsocial.com/@realDonaldTrump/117323155721195611',1329.0,3534.0,12560.0,'117323155721195611',27.0,'2026-09-20 14:00:00.000000'
117323148147220269,'2026-09-24 00:19:29','BIG DAY FOR BOEING AND AMERICAN MANUFACTURING! Today, Türkiye and Bangladesh announced purchases totaling 111 Boeing Airplanes—with options for 50 more—following support from Howard Lutnick and the Department of Commerce. TENS of BILLIONS of Dollars in Sales, and huge U.S. Exports, supporting tens of thousands of American Jobs across our Country. The Market is recognizing what Boeing and I have known all along: When you BUILD IN AMERICA, EXPORT FROM AMERICA, and SUPPORT AMERICAN WORKERS, you make your Company stronger. Congratulations to Boeing, and its incredible workforce! President DONALD J. TRUMP','https://truthsocial.com/@realDonaldTrump/117323148147220269',510.0,2714.0,10677.0,'117323148147220269',27.0,'2026-09-20 14:00:00.000000'
117322092055919832,'2026-09-23 19:50:55','','https://truthsocial.com/@realDonaldTrump/117322092055919832',1344.0,2740.0,11287.0,'117322092055919832',27.0,'2026-09-20 14:00:00.000000'
117322065119445871,'2026-09-23 19:44:04','The Great Gary Player, Bryson DeChambeau, Mikayla Demaiter, and Susan Waterfall, on Marine One! President DONALD J. TRUMP','https://truthsocial.com/@realDonaldTrump/117322065119445871',505.0,2156.0,10284.0,'117322065119445871',27.0,'2026-09-20 14:00:00.000000'
117320581360547091,'2026-09-23 13:26:43','Victor Davis Hanson on Canada — A MUST SEE! President DONALD J. TRUMP','https://truthsocial.com/@realDonaldTrump/117320581360547091',1408.0,4876.0,15158.0,'117320581360547091',27.0,'2026-09-20 14:00:00.000000'
117320509296515188,'2026-09-23 13:08:24',"Canada is destroying itself by allowing millions and millions of people into the Country, essentially unchecked and unvetted, and who are causing problems that will soon be too big to handle. It is a Liberal takeover that will end very badly. Already showing up in their numbers. Big unemployment. 'Oh Canada! President DJT",'https://truthsocial.com/@realDonaldTrump/117320509296515188',4354.0,7815.0,30624.0,'117320509296515188',27.0,'2026-09-20 14:00:00.000000'
117320385350427395,'2026-09-23 12:36:52','Thank you to the Great Robert Greenway and Jesse — They get it! President DONALD J. TRUMP','https://truthsocial.com/@realDonaldTrump/117320385350427395',831.0,4083.0,14660.0,'117320385350427395',27.0,'2026-09-20 14:00:00.000000'
117318371569831036,'2026-09-23 04:04:44',"Ruddy: 'A Rising Trump Lifts All Boats': https://www.newsmax.com/ruddy/ruddy-donald-trump-economy/2026/09/13/id/1269294/",'https://truthsocial.com/@realDonaldTrump/117318371569831036',956.0,3300.0,13650.0,'117318371569831036',27.0,'2026-09-20 14:00:00.000000'
117318370203435194,'2026-09-23 04:04:24',"Azerbaijan's Hajiyev to Newsmax: Trump Peacemaker, Iran Deal Possible: https://www.newsmax.com/newsfront/azerbaijan-ilham-aliyev-armenia/2026/09/14/id/1269433/",'https://truthsocial.com/@realDonaldTrump/117318370203435194',586.0,2858.0,12323.0,'117318370203435194',27.0,'2026-09-20 14:00:00.000000'
117318368847920040,'2026-09-23 04:04:03','Netanyahu Bloc Takes Lead in Latest Israeli Election Poll: https://www.newsmax.com/newsfront/israel-benjamin-netanyahu-likud/2026/09/17/id/1269830/','https://truthsocial.com/@realDonaldTrump/117318368847920040',630.0,2496.0,10851.0,'117318368847920040',27.0,'2026-09-20 14:00:00.000000'
117318365806497574,'2026-09-23 04:03:16','','https://truthsocial.com/@realDonaldTrump/117318365806497574',1197.0,3686.0,14111.0,'117318365806497574',27.0,'2026-09-20 14:00:00.000000'
117318329260090686,'2026-09-23 03:53:59','All of the SLEAZEBAGS, like Third Rate "Reporter," Kaitlan Collins, of Fake News CNN, a truly unhappy person, said they weren\'t going to be covering me. Then why were they ranting and raving like Lunatics, in the Press Area, at the United Nations? Why was she there? She\'s got a "TRUMP" addiction, and so does CNN and MSDNC. They\'re all sick, treasonous, and demented! The "good news" is that they have a great, for them, and totally disloyal Judge. MAKE AMERICA GREAT AGAIN! President DONALD J. TRUMP','https://truthsocial.com/@realDonaldTrump/117318329260090686',2102.0,4508.0,17701.0,'117318329260090686',27.0,'2026-09-20 14:00:00.000000'
117316991845409643,'2026-09-22 22:13:52','Agent in Jack Smith case says he was kept in dark that subpoenaed phone data belonged to Congress: https://justthenews.com/accountability/political-ethics/agent-jack-smith-case-says-he-was-kept-dark-subpoenaed-phone-data','https://truthsocial.com/@realDonaldTrump/117316991845409643',1419.0,3933.0,12418.0,'117316991845409643',27.0,'2026-09-20 14:00:00.000000'
117314399826449877,'2026-09-22 11:14:40',"The cowards and traitors would love to say the United States is low on munitions. It's not true. We have more munitions than we could ever possibly think of using, and are building them up now at levels we have never seen before. President DONALD J. TRUMP",'https://truthsocial.com/@realDonaldTrump/117314399826449877',3768.0,6360.0,27497.0,'117314399826449877',27.0,'2026-09-20 14:00:00.000000'
117312693997244079,'2026-09-22 04:00:52','Thanks Johnny. You are a total winner! President DJTSPORTS MLB Legend Johnny Damon Refuses To Apologize For His Opinion on President Trump: https://www.miamiherald.com/sports/article317314631.html','https://truthsocial.com/@realDonaldTrump/117312693997244079',1120.0,4516.0,22681.0,'117312693997244079',27.0,'2026-09-20 14:00:00.000000'
117312560106447861,'2026-09-22 03:26:49',"RT @Schoenlawhttps://www.wsj.com/opinion/americans-household-income-2025-census-bureau-2e2a9e36?st=9jyvTw.  The writer tries to make excuses to explain this great news but the facts are the facts:  Americans are doing better financially and the poverty level is dramatically down!  Let's give credit where it is due and celebrate good news for our country and fellow Americans!!! @realDonaldTrump",'https://truthsocial.com/@realDonaldTrump/117312560106447861',0.0,0.0,1.0,'117312560106447861',27.0,'2026-09-20 14:00:00.000000'
117312531137546490,'2026-09-22 03:19:27','Keep the lights on, sideline Big Brother: Trump EPA rollback could save ratepayers $310 billion: https://justthenews.com/government/federal-agencies/trumps-epa-gets-action-roots-out-30-billion-waste-fraud-and-abuse','https://truthsocial.com/@realDonaldTrump/117312531137546490',762.0,4146.0,16689.0,'117312531137546490',27.0,'2026-09-20 14:00:00.000000'

### Struttura del file ARFF


La relazione è denominata `trump_truths` e presenta 10 attributi: `id`, `timestamp`, `text`, `url`, `reply_count`, `retruth_count`, `like_count`, `external_id`, `author` e `time_scraped`.

In [6]:
#author è sempre 27

In [9]:
record_count = 0
data_started = False

with open("additional_truths.arff", "r", encoding="utf-8") as file:
    for line in file:
        line = line.strip()

        if line.lower() == "@data":
            data_started = True
            continue

        if data_started and line:
            record_count += 1

print("Numero di record:", record_count)

Numero di record: 35222

Pandas

In [27]:
#Prendi i primi 2 campi partendo da sinistra e gli ultimi 7 partendo da destra.
#Tutto quello che rimane in mezzo è il text. (che crea problemi nel capire se ogni riga ha gli stessi campi)
import pandas as pd

columns = [
    "id", "timestamp", "text", "url",
    "reply_count", "retruth_count", "like_count",
    "external_id", "author", "time_scraped"
]

records = []
data_started = False #serve a ignorare l'header

with open("additional_truths.arff", "r", encoding="utf-8") as file:
    for line in file:
        line = line.strip() #strip() elimina spazi e soprattutto il carattere di fine riga \n all’inizio/fine.

        if line.lower() == "@data":
            data_started = True
            continue

        if data_started and line:
            # I primi due campi vengono separati da sinistra
            left = line.split(",", 2)

            # Gli ultimi sette campi vengono separati da destra
            text_and_right = left[2].rsplit(",", 7)

            row = [left[0], left[1]] + text_and_right
            records.append(row)

df_additional = pd.DataFrame(records, columns=columns)

print("Dimensioni del dataset:", df_additional.shape)
display(df_additional.head())

Dimensioni del dataset: (35222, 10)

,id,timestamp,text,url,reply_count,retruth_count,like_count,external_id,author,time_scraped
0,117323511508375196,'2026-09-24 01:51:54','','https://truthsocial.com/@realDonaldTrump/1173...,792.0,1849.0,7259.0,'117323511508375196',27.0,'2026-09-20 14:00:00.000000'
1,117323155721195611,'2026-09-24 00:21:25',"""The story that the White House, or me, want t...",'https://truthsocial.com/@realDonaldTrump/1173...,1329.0,3534.0,12560.0,'117323155721195611',27.0,'2026-09-20 14:00:00.000000'
2,117323148147220269,'2026-09-24 00:19:29','BIG DAY FOR BOEING AND AMERICAN MANUFACTURING...,'https://truthsocial.com/@realDonaldTrump/1173...,510.0,2714.0,10677.0,'117323148147220269',27.0,'2026-09-20 14:00:00.000000'
3,117322092055919832,'2026-09-23 19:50:55','','https://truthsocial.com/@realDonaldTrump/1173...,1344.0,2740.0,11287.0,'117322092055919832',27.0,'2026-09-20 14:00:00.000000'
4,117322065119445871,'2026-09-23 19:44:04',"'The Great Gary Player, Bryson DeChambeau, Mik...",'https://truthsocial.com/@realDonaldTrump/1173...,505.0,2156.0,10284.0,'117322065119445871',27.0,'2026-09-20 14:00:00.000000'

### Struttura del DataFrame e valori mancanti

In [30]:
df_additional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35222 entries, 0 to 35221
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             35222 non-null  object
 1   timestamp      35222 non-null  object
 2   text           35222 non-null  object
 3   url            35222 non-null  object
 4   reply_count    35222 non-null  object
 5   retruth_count  35222 non-null  object
 6   like_count     35222 non-null  object
 7   external_id    35222 non-null  object
 8   author         35222 non-null  object
 9   time_scraped   35222 non-null  object
dtypes: object(10)
memory usage: 2.7+ MB

#### Verifica dei valori vuoti

In [33]:
for column in df_additional.columns:
    print(column, ":", (df_additional[column].str.strip() == "").sum())

id : 0
timestamp : 0
text : 0
url : 0
reply_count : 0
retruth_count : 0
like_count : 0
external_id : 0
author : 0
time_scraped : 0

In [43]:
#not working

In [35]:
def remove_quotes(value):
    value = value.strip()

    if len(value) >= 2:
        if (value[0] == "'" and value[-1] == "'") or \
           (value[0] == '"' and value[-1] == '"'):
            return value[1:-1]

    return value

In [37]:
df_additional = pd.DataFrame(records, columns=columns)

In [39]:
for column in df_additional.columns:
    df_additional[column] = df_additional[column].apply(remove_quotes)

In [41]:
for column in df_additional.columns:
    print(column, ":", (df_additional[column].str.strip() == "").sum())

id : 0
timestamp : 0
text : 7262
url : 0
reply_count : 0
retruth_count : 0
like_count : 0
external_id : 0
author : 0
time_scraped : 0

#### Conversione dei tipi di dato

Poiché il DataFrame è stato costruito a partire dalla lettura testuale del file ARFF, Pandas ha inizialmente rappresentato tutti gli attributi come `object`.

In [47]:
df_additional["id"] = pd.to_numeric(df_additional["id"])

numeric_columns = [
    "reply_count",
    "retruth_count",
    "like_count",
    "author"
]

for column in numeric_columns:
    df_additional[column] = pd.to_numeric(df_additional[column])

ValueError: Unable to parse string "nan" at position 10943

In [ ]:
#non funziona per via dei "nan"

In [49]:
for column in ["reply_count", "retruth_count", "like_count", "author"]:
    print(column, ":", (df_additional[column].str.lower() == "nan").sum())

reply_count : 9
retruth_count : 9
like_count : 9
author : 0

In [51]:
nan_engagement = df_additional[
    (df_additional["reply_count"].str.lower() == "nan") |
    (df_additional["retruth_count"].str.lower() == "nan") |
    (df_additional["like_count"].str.lower() == "nan")
]

display(nan_engagement)

,id,timestamp,text,url,reply_count,retruth_count,like_count,external_id,author,time_scraped
10943,114135887529701366,2025-03-10 02:57:12,"Malcolm Turnbull, the former Prime Minister of...",https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135887529701366,27.0,2026-09-20 14:00:00.000000
10944,114135672415463032,2025-03-10 02:02:29,Great job by Congressman Brian Mast on FoxNews...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135672415463032,27.0,2026-09-20 14:00:00.000000
10945,114135406628804244,2025-03-10 00:54:54,"We're going to become so rich, you're not gonn...",https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135406628804244,27.0,2026-09-20 14:00:00.000000
10946,114135400416790297,2025-03-10 00:53:19,Democrats are out of control—They've lost thei...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135400416790297,27.0,2026-09-20 14:00:00.000000
10947,114135394676135924,2025-03-10 00:51:51,I want a dynamic Country where private enterpr...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135394676135924,27.0,2026-09-20 14:00:00.000000
10948,114135388919019484,2025-03-10 00:50:24,Nobody has been tougher on Russia than Donald ...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135388919019484,27.0,2026-09-20 14:00:00.000000
10949,114135383571986279,2025-03-10 00:49:02,The Carter Administration gave the Panama Cana...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135383571986279,27.0,2026-09-20 14:00:00.000000
10950,114135377964485025,2025-03-10 00:47:36,I’m not going to touch Social Security—We’re g...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135377964485025,27.0,2026-09-20 14:00:00.000000
10951,114135068157531979,2025-03-09 23:28:49,As I made clear during my Joint Address to Con...,https://truthsocial.com/@realDonaldTrump/11413...,nan,nan,nan,114135068157531979,27.0,2026-09-20 14:00:00.000000

sono gli stessi 9 record

In [54]:
#conversione
numeric_columns = [
    "reply_count",
    "retruth_count",
    "like_count",
    "author"
]

for column in numeric_columns:
    df_additional[column] = pd.to_numeric(
        df_additional[column],
        errors="coerce"
    )

In [56]:
df_additional.dtypes

id                 int64
timestamp         object
text              object
url               object
reply_count      float64
retruth_count    float64
like_count       float64
external_id       object
author           float64
time_scraped      object
dtype: object

In [58]:
df_additional[numeric_columns].isna().sum()

reply_count      9
retruth_count    9
like_count       9
author           0
dtype: int64

### Analisi dei valori mancanti

considerando sia i valori `NaN` riconosciuti da Pandas sia le stringhe vuote presenti negli attributi testuali.

In [62]:
missing_values = {}

for column in df_additional.columns:
    nan_count = df_additional[column].isna().sum()

    if df_additional[column].dtype == "object":
        empty_count = (df_additional[column].str.strip() == "").sum()
    else:
        empty_count = 0

    missing_values[column] = nan_count + empty_count

missing_values = pd.Series(missing_values)

print(missing_values)
print("\nTotale valori mancanti:", missing_values.sum())

id                  0
timestamp           0
text             7262
url                 0
reply_count         9
retruth_count       9
like_count          9
external_id         0
author              0
time_scraped        0
dtype: int64

Totale valori mancanti: 7289

### Analisi degli identificativi

`id` ed `external_id`

In [66]:
print("Record totali:", len(df_additional))

print("\nID distinti:", df_additional["id"].nunique())
print("ID duplicati:", df_additional["id"].duplicated().sum())

print("\nExternal ID distinti:", df_additional["external_id"].nunique())
print("External ID duplicati:", df_additional["external_id"].duplicated().sum())

Record totali: 35222

ID distinti: 35222
ID duplicati: 0

External ID distinti: 35222
External ID duplicati: 0

Non sono quindi presenti identificativi duplicati ed entrambi gli attributi risultano univoci all'interno del dataset.

#### Confronto tra `id` ed `external_id`

In [70]:
same_id = (
    df_additional["id"].astype(str) == df_additional["external_id"]
)

print("Record con ID uguali:", same_id.sum())
print("Record con ID diversi:", (~same_id).sum())

Record con ID uguali: 35222
Record con ID diversi: 0

I due attributi risultano quindi ridondanti

### Analisi degli attributi temporali

In [74]:
timestamp_dt = pd.to_datetime(
    df_additional["timestamp"],
    errors="coerce"
)

time_scraped_dt = pd.to_datetime(
    df_additional["time_scraped"],
    errors="coerce"
)

print("Timestamp non convertibili:", timestamp_dt.isna().sum())
print("Time scraped non convertibili:", time_scraped_dt.isna().sum())

Timestamp non convertibili: 0
Time scraped non convertibili: 0

In [76]:
print("Timestamp minimo:", timestamp_dt.min())
print("Timestamp massimo:", timestamp_dt.max())

print("\nTime scraped minimo:", time_scraped_dt.min())
print("Time scraped massimo:", time_scraped_dt.max())

Timestamp minimo: 2022-04-28 21:29:28
Timestamp massimo: 2026-09-24 01:51:54

Time scraped minimo: 2026-09-20 14:00:00
Time scraped massimo: 2026-09-20 14:00:00

In [79]:
posts_after_scrape = timestamp_dt > time_scraped_dt

print(
    "Post con timestamp successivo a time_scraped:",
    posts_after_scrape.sum()
)

Post con timestamp successivo a time_scraped: 42

In [81]:
display(
    df_additional.loc[
        posts_after_scrape,
        ["id", "timestamp", "time_scraped"]
    ]
)

                    id            timestamp                time_scraped
0   117323511508375196  2026-09-24 01:51:54  2026-09-20 14:00:00.000000
1   117323155721195611  2026-09-24 00:21:25  2026-09-20 14:00:00.000000
2   117323148147220269  2026-09-24 00:19:29  2026-09-20 14:00:00.000000
3   117322092055919832  2026-09-23 19:50:55  2026-09-20 14:00:00.000000
4   117322065119445871  2026-09-23 19:44:04  2026-09-20 14:00:00.000000
5   117320581360547091  2026-09-23 13:26:43  2026-09-20 14:00:00.000000
6   117320509296515188  2026-09-23 13:08:24  2026-09-20 14:00:00.000000
7   117320385350427395  2026-09-23 12:36:52  2026-09-20 14:00:00.000000
8   117318371569831036  2026-09-23 04:04:44  2026-09-20 14:00:00.000000
9   117318370203435194  2026-09-23 04:04:24  2026-09-20 14:00:00.000000
10  117318368847920040  2026-09-23 04:04:03  2026-09-20 14:00:00.000000
11  117318365806497574  2026-09-23 04:03:16  2026-09-20 14:00:00.000000
12  117318329260090686  2026-09-23 03:53:59  2026-09-20 14:00:00.000000
13  117316991845409643  2026-09-22 22:13:52  2026-09-20 14:00:00.000000
14  117314399826449877  2026-09-22 11:14:40  2026-09-20 14:00:00.000000
15  117312693997244079  2026-09-22 04:00:52  2026-09-20 14:00:00.000000
16  117312560106447861  2026-09-22 03:26:49  2026-09-20 14:00:00.000000
17  117312531137546490  2026-09-22 03:19:27  2026-09-20 14:00:00.000000
18  117310775870715938  2026-09-21 19:53:03  2026-09-20 14:00:00.000000
19  117310724294153031  2026-09-21 19:39:56  2026-09-20 14:00:00.000000
20  117310502008279319  2026-09-21 18:43:24  2026-09-20 14:00:00.000000
21  117310501298755407  2026-09-21 18:43:14  2026-09-20 14:00:00.000000
22  117310494630713204  2026-09-21 18:41:32  2026-09-20 14:00:00.000000
23  117310364553695688  2026-09-21 18:08:27  2026-09-20 14:00:00.000000
24  117310166479352147  2026-09-21 17:18:05  2026-09-20 14:00:00.000000
25  117309814170246776  2026-09-21 15:48:29  2026-09-20 14:00:00.000000
26  117309799376551907  2026-09-21 15:44:43  2026-09-20 14:00:00.000000
27  117309573610238654  2026-09-21 14:47:18  2026-09-20 14:00:00.000000
28  117308930224398545  2026-09-21 12:03:41  2026-09-20 14:00:00.000000
29  117308890736529824  2026-09-21 11:53:38  2026-09-20 14:00:00.000000
30  117307292070204943  2026-09-21 05:07:05  2026-09-20 14:00:00.000000
31  117307289681145880  2026-09-21 05:06:28  2026-09-20 14:00:00.000000
32  117307260504631667  2026-09-21 04:59:03  2026-09-20 14:00:00.000000
33  117307257715841389  2026-09-21 04:58:20  2026-09-20 14:00:00.000000
34  117307255154500060  2026-09-21 04:57:41  2026-09-20 14:00:00.000000
35  117306567834657729  2026-09-21 02:02:54  2026-09-20 14:00:00.000000
36  117306342307545273  2026-09-21 01:05:32  2026-09-20 14:00:00.000000
37  117305526182125195  2026-09-20 21:37:59  2026-09-20 14:00:00.000000
38  117305110887067544  2026-09-20 19:52:22  2026-09-20 14:00:00.000000
39  117305110118463243  2026-09-20 19:52:11  2026-09-20 14:00:00.000000
40  117305109272193640  2026-09-20 19:51:58  2026-09-20 14:00:00.000000
41  117304284426928910  2026-09-20 16:22:12  2026-09-20 14:00:00.000000

sono stati individuati **42 record** nei quali il `timestamp` di pubblicazione è successivo al valore di `time_scraped`.

### Analisi dell'attributo `author`

In [85]:
print("Autori distinti:", df_additional["author"].nunique())

print("\nFrequenza degli autori:")
display(df_additional["author"].value_counts().head(10))

Autori distinti: 1

Frequenza degli autori:

author
27.0    35222
Name: count, dtype: int64

l'attributo `author` assume un unico valore, pari a `27`. `additional_truths.arff` contiene quindi esclusivamente post associati allo stesso autore.

### Analisi degli attributi di engagement

In [91]:
engagement_columns = [
    "reply_count",
    "retruth_count",
    "like_count"
]

df_additional[engagement_columns].describe().round(2)

       reply_count  retruth_count  like_count
count     35213.00       35213.00    35213.00
mean        798.93        3273.24    12890.84
std        1351.25        2966.21    11553.46
min           0.00           0.00        0.00
25%         125.00        1460.00     5697.00
50%         398.00        2808.00    11136.00
75%         988.00        4482.00    17596.00
max       60886.00      123196.00   410837.00

### Analisi dei valori massimi di engagement

In [95]:
for column in engagement_columns:
    print("\nMassimo", column, ":", df_additional[column].max())
    
    display(
        df_additional.loc[
            df_additional[column] == df_additional[column].max(),
            ["id", "timestamp", "text", column]
        ]
    )

Massimo reply_count : 60886.0

,id,timestamp,text,reply_count
35221,108211822140637685,2022-04-28 21:29:28,I’M BACK! #COVFEFE,60886.0

Massimo retruth_count : 123196.0

,id,timestamp,text,retruth_count
35221,108211822140637685,2022-04-28 21:29:28,I’M BACK! #COVFEFE,123196.0

Massimo like_count : 410837.0

                       id            timestamp                text  like_count
35221  108211822140637685  2022-04-28 21:29:28  I’M BACK! #COVFEFE    410837.0

i valori massimi dei tre attributi di engagement appartengono allo stesso record, relativo al post "I’M BACK! #COVFEFE"

### Analisi dei record duplicati

In [99]:
duplicated_rows = df_additional.duplicated().sum()

print("Record completamente duplicati:", duplicated_rows)

Record completamente duplicati: 0

### Analisi dell'attributo `text`

In [102]:
empty_text = df_additional["text"].str.strip() == ""

display(
    df_additional.loc[
        empty_text,
        ["id", "timestamp", "text", "url",
         "reply_count", "retruth_count", "like_count"]
    ].head(10)
)

,id,timestamp,text,url,reply_count,retruth_count,like_count
0,117323511508375196,2026-09-24 01:51:54,,https://truthsocial.com/@realDonaldTrump/11732...,792.0,1849.0,7259.0
3,117322092055919832,2026-09-23 19:50:55,,https://truthsocial.com/@realDonaldTrump/11732...,1344.0,2740.0,11287.0
11,117318365806497574,2026-09-23 04:03:16,,https://truthsocial.com/@realDonaldTrump/11731...,1197.0,3686.0,14111.0
37,117305526182125195,2026-09-20 21:37:59,,https://truthsocial.com/@realDonaldTrump/11730...,1490.0,3425.0,15092.0
38,117305110887067544,2026-09-20 19:52:22,,https://truthsocial.com/@realDonaldTrump/11730...,1424.0,3640.0,14039.0
39,117305110118463243,2026-09-20 19:52:11,,https://truthsocial.com/@realDonaldTrump/11730...,839.0,3830.0,13683.0
40,117305109272193640,2026-09-20 19:51:58,,https://truthsocial.com/@realDonaldTrump/11730...,506.0,3335.0,12919.0
41,117304284426928910,2026-09-20 16:22:12,,https://truthsocial.com/@realDonaldTrump/11730...,2276.0,5741.0,22903.0
42,117303611907345909,2026-09-20 13:31:10,,https://truthsocial.com/@realDonaldTrump/11730...,1037.0,4002.0,15345.0
46,117298879209243512,2026-09-19 17:27:35,,https://truthsocial.com/@realDonaldTrump/11729...,2330.0,6511.0,27636.0

### Analisi dell'attributo `url`

In [106]:
expected_prefix = "https://truthsocial.com/@realDonaldTrump/"

valid_url = df_additional["url"].str.startswith(expected_prefix)

print("URL con struttura attesa:", valid_url.sum())
print("URL con struttura diversa:", (~valid_url).sum())

URL con struttura attesa: 35222
URL con struttura diversa: 0

tutti i 35.522 record presentano un URL che inizia con `https://truthsocial.com/@realDonaldTrump/`.

### Coerenza tra `url` e identificativo del post

In [110]:
url_ends_with_id = df_additional.apply(
    lambda row: row["url"].endswith("/" + str(row["id"])),
    axis=1
)

print("URL coerenti con id:", url_ends_with_id.sum())
print("URL non coerenti con id:", (~url_ends_with_id).sum())

URL coerenti con id: 35222
URL non coerenti con id: 0

### Distribuzione temporale dei post

In [114]:
posts_per_year = timestamp_dt.dt.year.value_counts().sort_index()

display(posts_per_year)

timestamp
2022     2707
2023     9905
2024    10587
2025     6229
2026     5794
Name: count, dtype: int64